spring.application.name=vehicle-service
server.port=8084
spring.datasource.url=jdbc:mysql://bd-vehiculo:3306/sicaeVehiculo?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=UserPapu
spring.datasource.password=Papulin
app.jwtSecret=4qHQ+mbQG9NfP/6r7v/M0bT2G8dO9pYq3U4n7w6sR5t=
app.jwtExpirationMs=86400000