spring.application.name=vehicle-service
server.port=8084
spring.datasource.url=jdbc:mysql://BD_Vehiculo:3306/sicaeVehiculo?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=UserPapu
spring.datasource.password=Papulin