version: '3.8'

services:
  bd-vehiculo:
    image: mysql:8.0.45
    container_name: BD_Vehiculo
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: sicaeVehiculo
      MYSQL_USER: UserPapu
      MYSQL_PASSWORD: Papulin
    ports:
      - "3306:3306"
    volumes:
      - ./ScriptBD/sicaevehiculo.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always