version: '3.8'

services:
  bd-estacionamiento:
    image: mysql:8.0.45
    container_name: BD_Estacionamiento
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: sicaeEstacionamiento
      MYSQL_USER: UserPapu
      MYSQL_PASSWORD: Papulin
    ports:
      - "3307:3306"
    volumes:
      - ./ScriptBD/sicaeestacionamiento.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always